/*
 * Created on 14.09.2004
 *
 * TODO To change the template for this generated file go to
 * Window - Preferences - Java - Code Style - Code Templates
 */
package de.nrw.dipp.dippCore.service;

import java.io.IOException;
import java.util.Calendar;
import java.util.Timer;

import javax.servlet.ServletConfig;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import de.nrw.dipp.dippCore.gap.GapManagement;
import de.nrw.dipp.dippCore.util.Constant;

import org.apache.log4j.Logger;





/**
 * <p>A Servlet has provided a sheduler for calling the GapManagement Class<br />
 * it was startet automatically each time the DiPP Service Servlet-Container is deployed</p>
 * <p> GaPWorkflow will be replaced soon and GaPManagementServlet willnot be called any longer</p>   
 * 
 * @author SCHIRRWAGEN
 * 
 *
 */
public class DippServlet extends HttpServlet {
    private Timer timer;
//    private static int cSecondsGapExport = 60;
//    private static int cSecondsManual = 5; //86400;
//    private static int cSecondsOfDay	= 3600;

    //get Logger instance
    private Logger log = Logger.getLogger(DippServlet.class);
	
    public void init(ServletConfig config) throws ServletException {
		super.init(config);
//		de.nrw.dipp.util.request.MimeType.getInstance(getServletContext().getResourceAsStream("/WEB-INF/mimetype.xml"));
		Constant.setAbsolutPath(getServletContext().getRealPath("/"));
	}

	public void init()throws ServletException{
		super.init();
		Constant.setAbsolutPath(getServletContext().getRealPath("/"));
        Constant.initLog();
        log.info("\n *     Digital Peer Publishing DiPP     *   \n" + getServletInfo());
		timer = new Timer(true);
        String oaiGapStr = "";
        int oaiGapInt = 60;
        if ( (oaiGapStr = getServletContext().getInitParameter("oaiGapIntervall")) != null){
        	oaiGapInt = Integer.parseInt(oaiGapStr);
        }
        Calendar cal = Calendar.getInstance();
//        cal.set(Calendar.HOUR_OF_DAY, 23);
//        cal.set(Calendar.MINUTE, 45);
/*        timer.schedule(new GapManagement(),
                      cal.getTime(), oaiGapInt * 1000); */   
//        timer.schedule(new FileTask(), cal.getTime(), cSecondsOfDay * 1000 );
//        System.out.println("GapServlet: " + Constant.getAbsolutPath());
	}
	public void destroy() {
		super.destroy();
        timer.cancel();
	}

	protected void doGet(HttpServletRequest request,
			HttpServletResponse response) throws ServletException, IOException {
		//TODO Method stub generated by Lomboz
		doPost(request, response);
	}

	protected void doPost(HttpServletRequest request,
			HttpServletResponse response) throws ServletException, IOException {
	}
	
	public String getServletInfo() {
		return " *     " + Constant.cInfoAuthor + "\n" 
			   + " *     "  + Constant.cInfoVersion + Constant.cInfoSubVersion + "\n" 
			   + " *     "  + Constant.cInfoCopyRight;
	}
}
